### ISSUE TITLE
nuuu... enumul nu poate avea fielduri variabile (gen activities), ci doar chestii care tin de enum (nume, ordinea in saptamana, etc)

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#10]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex4/WeekDays.java#L4

**Comment by cezarhre** [comment]
Am modificat
