### ISSUE TITLE
range-ul trebuie sa fie dinamic. toate masinile trebuie sa fie in mapa. la fel si la pret

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#14]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex5/CarShop.java#L39

**Comment by cezarhre** [comment]
am pus parametru
