### ISSUE TITLE
aceeasi problema.. adu-mi aminte la curs sa discutam, nu e acceptabil sa mearga destul de bine metodele, dar sa faci greseala asta... trebuie clarificat

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#17]
https://github.com/cezarhre/curs12.homework/blob/d9d4274331a2bfbb9ab5de8909b065a6c6010c88/src/ro/fasttrackit/curs12/homework/ex3/Employees.java#L9

**Comment by cezarhre** [comment]
Am refacut. Cred ca asta era solutia...
