### ISSUE TITLE
nope... nu merge.. mai gandeste-te la ce faci

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#18]
https://github.com/cezarhre/curs12.homework/blob/d9d4274331a2bfbb9ab5de8909b065a6c6010c88/src/ro/fasttrackit/curs12/homework/ex3/Employees.java#L53

**Comment by cezarhre** [comment]
Nu inteleg de ce nu merge. Imi returneaza compania care acorda cel mai mare salariu...
