### ISSUE TITLE
tie nu-ti plac parametrii ... asa-i? De ce nu putea fi aceasta lista construita in main si trimisa ca parametru acestei metode. Astfel, puteai pune ORICE range, nu doar asta pe care il construiesti aici

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#20]
https://github.com/cezarhre/curs12.homework/blob/d9d4274331a2bfbb9ab5de8909b065a6c6010c88/src/ro/fasttrackit/curs12/homework/ex5/CarShop.java#L34

**Comment by cezarhre** [comment]
sunt la inceput... nu le vad inca
