### ISSUE TITLE
18 trebuia sa fie dat prin parametru. Asa tu ai facut o metoda care proceseaza doar persoanele majore.

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#3]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex2/PersonList.java#L26

**Comment by cezarhre** [comment]
Am introdus parametru
