### ISSUE TITLE
daca tot ce faci in suprascriere e ca apelezi parintele, n-o face. Asta e ideea la mostenire, ca nu trebuie sa rescrii metodele care sunt ok in parinte!

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#6]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex3/Employee.java#L24

**Comment by cezarhre** [comment]
OK Am reviziut
