### ISSUE TITLE
nuu... trebuie sa verifici toate persoanele ca sa vezi care are salariu cel mai mare. Esti f. aproape de solutie corecta.

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#8]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex3/Employees.java#L51

**Comment by cezarhre** [comment]
In cerinta scrie care companie acorda salariul cel mai mare...
Am facut si pentru salariat
