### ISSUE TITLE
te joci cu focul aici. Ai o variabila locala care e acelasi nume cu fieldul. Evita asa ceva. Poti zice companyEmployees

### ISSUE THREAD

**Issue by stefanbulzan** [cezarhre/curs12.homework#9]
https://github.com/cezarhre/curs12.homework/blob/ee60f829b3dc7c8c4dbe738f41c53e588f8d1eda/src/ro/fasttrackit/curs12/homework/ex3/Employees.java#L28

**Comment by cezarhre** [comment]
Am corectat
